In [82]:
import re
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import svm
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import Binarizer
from sklearn.metrics import accuracy_score, precision_score , recall_score , confusion_matrix
from sklearn.model_selection import GridSearchCV
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [70]:
import pandas as pd

df=pd.read_csv('C:/1차data/3.19.csv',encoding='cp949')
df

,고객번호,성별,연령대,거주지역,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),4번품목구매비율(%),경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1기구매비율(%),2기구매비율(%),3기구매비율(%),4기구매비율(%),5기구매비율(%),6기구매비율(%),7기구매비율(%),8기구매비율(%),분기증감확인
0,1,1,5,1,2.86,27.70,66.92,2.52,15.0,0.0,0.0,11.46,14.63,13.22,14.90,8.43,10.15,18.56,8.65,0
1,2,1,5,0,3.64,36.73,53.35,6.28,8.0,0.0,0.0,10.30,9.24,16.44,6.49,17.57,11.73,16.87,11.36,0
2,3,1,5,0,4.47,95.53,0.00,0.00,0.0,0.0,0.0,9.88,12.45,13.71,11.11,14.96,11.62,15.71,10.56,0
3,4,0,5,1,2.72,26.13,66.48,4.67,3.0,0.0,0.0,9.35,14.65,21.83,12.53,9.71,9.85,13.69,8.39,0
4,6,0,5,3,4.99,45.59,40.38,9.04,0.0,0.0,0.0,8.86,13.33,16.02,11.16,12.32,14.81,13.86,9.64,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,15.53,55.08,0.00,29.39,0.0,1.0,5.0,11.51,11.72,15.37,7.99,13.80,15.52,13.97,10.12,0
18862,19334,1,2,3,13.88,66.70,0.00,19.42,30.0,1.0,0.0,10.03,9.05,9.48,11.36,11.80,7.81,27.53,12.94,0
18863,19335,0,2,0,16.72,53.31,0.00,29.97,0.0,1.0,0.0,13.37,13.37,13.17,9.74,10.97,17.91,11.52,9.94,1
18864,19336,0,2,1,10.66,30.64,54.74,3.96,0.0,0.0,0.0,9.27,7.35,7.48,11.51,7.79,19.75,23.40,13.44,1
18865,19337,1,1,1,6.46,93.54,0.00,0.00,0.0,0.0,0.0,8.18,12.43,12.43,14.14,13.50,11.38,15.87,12.07,1

In [28]:
df.columns

Index(['고객번호', '성별', '연령대', '거주지역', '1번품목구매비율(%)', '2번품목구매비율(%)',
       '3번품목구매비율(%)', '4번품목구매비율(%)', '경쟁사이용횟수', '멤버쉽보유', '온라인이용횟수',
       '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)', '5기구매비율(%)',
       '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)', '분기증감확인'],
      dtype='object')

In [128]:
from sklearn.preprocessing import StandardScaler
stcol=['1번품목구매비율(%)', '2번품목구매비율(%)',
       '3번품목구매비율(%)', '4번품목구매비율(%)',
      '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)', '5기구매비율(%)',
       '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)',
      '경쟁사이용횟수','멤버쉽보유','온라인이용횟수']

for i in stcol:
    sc = StandardScaler()
    sc.fit(df[[i]])
    df[i] = sc.transform(df[[i]])
df

,고객번호,성별,연령대,거주지역,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),4번품목구매비율(%),경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1기구매비율(%),2기구매비율(%),3기구매비율(%),4기구매비율(%),5기구매비율(%),6기구매비율(%),7기구매비율(%),8기구매비율(%),분기증감확인
0,1,1,5,1,-0.630974,-0.755058,1.078629,-0.835903,3.784157,-0.652472,-0.424659,-0.232993,0.461691,0.002362,0.679744,-0.915534,-0.558190,1.083053,-0.543234,0
1,2,1,5,0,-0.525165,-0.394411,0.679567,-0.596377,1.828781,-0.652472,-0.424659,-0.443681,-0.682709,0.700460,-1.199224,1.146230,-0.195524,0.744137,-0.027620,0
2,3,1,5,0,-0.412574,1.953988,-0.889331,-0.996436,-0.405935,-0.652472,-0.424659,-0.519964,-0.001164,0.108594,-0.167020,0.557477,-0.220773,0.511509,-0.179831,0
3,4,0,5,1,-0.649966,-0.817762,1.065689,-0.698940,0.432083,-0.652472,-0.424659,-0.616226,0.465938,1.869016,0.150237,-0.626797,-0.627051,0.106415,-0.592702,0
4,6,0,5,3,-0.342034,-0.040554,0.298150,-0.420556,-0.405935,-0.652472,-0.424659,-0.705224,0.185676,0.609404,-0.155849,-0.038043,0.511444,0.140507,-0.354873,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,1.087744,0.338465,-0.889331,0.875812,-0.405935,1.068660,-0.084953,-0.223912,-0.156157,0.468484,-0.864093,0.295809,0.674414,0.162567,-0.263547,0
18862,19334,1,2,3,0.863918,0.802553,-0.889331,0.240687,7.974248,1.068660,-0.424659,-0.492720,-0.723049,-0.808473,-0.111165,-0.155343,-1.095303,2.881910,0.272996,0
18863,19335,0,2,0,1.249171,0.267773,-0.889331,0.912760,-0.405935,1.068660,-0.424659,0.113914,0.194169,-0.008478,-0.473107,-0.342571,1.223004,-0.328760,-0.297794,1
18864,19336,0,2,1,0.427116,-0.637638,0.720444,-0.744170,-0.405935,-0.652472,-0.424659,-0.630757,-1.083992,-1.242074,-0.077652,-1.059902,1.645349,2.053673,0.368127,1
18865,19337,1,1,1,-0.142625,1.874509,-0.889331,-0.996436,-0.405935,-0.652472,-0.424659,-0.828730,-0.005411,-0.168910,0.509944,0.228136,-0.275862,0.543596,0.107467,1

In [129]:
lst=['성별','연령대','거주지역']

ddf=pd.get_dummies(df[lst[0]])
ddf.columns=['성별1','성별2']
onehot=pd.concat([df,ddf],axis=1)    
onehot

ddf=pd.get_dummies(df[lst[1]])
ddf.columns=['연령대1','연령대2','연령대3','연령대4','연령대5','연령대6']
onehot=pd.concat([onehot,ddf],axis=1)    
onehot

ddf=pd.get_dummies(df[lst[2]])
ddf.columns=['거주1','거주2','거주3','거주4',]
onehot=pd.concat([onehot,ddf],axis=1)    
onehot

,고객번호,성별,연령대,거주지역,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),4번품목구매비율(%),경쟁사이용횟수,멤버쉽보유,...,연령대1,연령대2,연령대3,연령대4,연령대5,연령대6,거주1,거주2,거주3,거주4
0,1,1,5,1,-0.630974,-0.755058,1.078629,-0.835903,3.784157,-0.652472,...,0,0,0,0,0,1,0,1,0,0
1,2,1,5,0,-0.525165,-0.394411,0.679567,-0.596377,1.828781,-0.652472,...,0,0,0,0,0,1,1,0,0,0
2,3,1,5,0,-0.412574,1.953988,-0.889331,-0.996436,-0.405935,-0.652472,...,0,0,0,0,0,1,1,0,0,0
3,4,0,5,1,-0.649966,-0.817762,1.065689,-0.698940,0.432083,-0.652472,...,0,0,0,0,0,1,0,1,0,0
4,6,0,5,3,-0.342034,-0.040554,0.298150,-0.420556,-0.405935,-0.652472,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,1.087744,0.338465,-0.889331,0.875812,-0.405935,1.068660,...,0,1,0,0,0,0,1,0,0,0
18862,19334,1,2,3,0.863918,0.802553,-0.889331,0.240687,7.974248,1.068660,...,0,0,1,0,0,0,0,0,0,1
18863,19335,0,2,0,1.249171,0.267773,-0.889331,0.912760,-0.405935,1.068660,...,0,0,1,0,0,0,1,0,0,0
18864,19336,0,2,1,0.427116,-0.637638,0.720444,-0.744170,-0.405935,-0.652472,...,0,0,1,0,0,0,0,1,0,0
18865,19337,1,1,1,-0.142625,1.874509,-0.889331,-0.996436,-0.405935,-0.652472,...,0,1,0,0,0,0,0,1,0,0

In [144]:
onehot.corr()['분기증감확인']

고객번호           0.000697
성별            -0.010664
연령대           -0.030961
거주지역           0.000018
1번품목구매비율(%)   -0.077652
2번품목구매비율(%)   -0.050620
3번품목구매비율(%)    0.089658
4번품목구매비율(%)   -0.077013
경쟁사이용횟수        0.019390
멤버쉽보유          0.014491
온라인이용횟수        0.017091
1기구매비율(%)     -0.282714
2기구매비율(%)     -0.049685
3기구매비율(%)     -0.048493
4기구매비율(%)      0.028228
5기구매비율(%)     -0.022266
6기구매비율(%)      0.033062
7기구매비율(%)      0.020669
8기구매비율(%)      0.330984
분기증감확인         1.000000
성별1            0.010664
성별2           -0.010664
연령대1           0.007411
연령대2           0.036030
연령대3           0.030006
연령대4          -0.033194
연령대5          -0.013600
연령대6           0.007977
거주1           -0.033401
거주2            0.050836
거주3            0.002540
거주4           -0.037469
Name: 분기증감확인, dtype: float64

In [150]:
X.columns

Index(['성별1', '성별2', '연령대1', '연령대2', '연령대3', '연령대4', '연령대5', '연령대6', '거주1',
       '거주2', '거주3', '거주4'],
      dtype='object')

In [183]:
# X = df.drop(['고객번호','분기증감확인'],axis=1)
# y=df[['분기증감확인']]
# X = onehot.drop(['1번품목구매비율(%)', '2번품목구매비율(%)', '3번품목구매비율(%)', '4번품목구매비율(%)', '경쟁사이용횟수',
#        '멤버쉽보유', '온라인이용횟수', '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)',
#        '5기구매비율(%)', '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)','고객번호','분기증감확인','성별','연령대','거주지역', '거주1',
#        '거주2', '거주3', '거주4', '연령대1', '연령대2', '연령대3', '연령대4', '연령대5', '연령대6',	'성별1','성별2'],axis=1)

X = onehot.drop(['1번품목구매비율(%)', '2번품목구매비율(%)', '3번품목구매비율(%)', '4번품목구매비율(%)', '경쟁사이용횟수',
       '멤버쉽보유', '온라인이용횟수', '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)',
       '5기구매비율(%)', '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)','고객번호','분기증감확인','성별','연령대','거주지역', '거주1',
       '거주2', '거주3', '거주4', '연령대1', '연령대2', '연령대3', '연령대4', '연령대5', '연령대6',	'성별1','성별2'],axis=1)
y=df[['분기증감확인']]
X

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[18866 rows x 0 columns]

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=10)

In [182]:
%%time
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.3f}'.format(accuracy_score(y_test, dt_pred)))

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도: {0:.3f}'.format(accuracy_score(y_test, rf_pred)))
                                                                  

lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
lr_preds = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {:0.3f}'.format(accuracy_score(y_test, lr_preds)))

lgbm_wrapper = LGBMClassifier(n_estimators=400)
evals = [(X_test,y_test)]
lgbm_wrapper.fit(X_train, y_train, eval_set=evals, verbose=False)
preds = lgbm_wrapper.predict(X_test)
print('lgbm 정확도: {:0.3f}'.format(accuracy_score(y_test, preds)))


evals = [(X_test,y_test)]
xgb_wrapper = XGBClassifier(n_estimators=400, learning_rate=0.1, max_depth=3)
xgb_wrapper.fit(X_train,y_train, early_stopping_rounds = 100, eval_set=evals, eval_metric='logloss', verbose=False)
w_preds = xgb_wrapper.predict(X_test)
print('xgbm 정확도: {:0.3f}'.format(accuracy_score(y_test, w_preds)))


k_model = KNeighborsClassifier(n_neighbors=40)
k_model.fit(X_train,y_train)
k_pred = k_model.predict(X_test)
k_accuracy = accuracy_score(y_test,k_pred)
print('KNN 예측 정확도: {:0.3f}'. format(k_accuracy))


svm_model = svm.SVC(kernel='rbf')
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test,svm_pred)
print('SVM 예측정확도: {:0.3f}'.format(svm_accuracy))


lr_clf = LogisticRegression()
knn_clf = KNeighborsClassifier(n_neighbors=8)
vo_clf = VotingClassifier( estimators=[('LR',lr_clf),('KNN',knn_clf)] , voting='soft' )
vo_clf.fit(X_train , y_train)
pred = vo_clf.predict(X_test)
print('Voting 분류기 정확도: {0:.3f}'.format(accuracy_score(y_test , pred)))

DecisionTreeClassifier 정확도: 0.629
RandomForestClassifier 정확도: 0.716
LogisticRegression 정확도: 0.712
lgbm 정확도: 0.719
xgbm 정확도: 0.716
KNN 예측 정확도: 0.675
SVM 예측정확도: 0.716
Voting 분류기 정확도: 0.695
Wall time: 41.6 s