In [34]:
import re
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import svm
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import Binarizer
from sklearn.metrics import accuracy_score, precision_score , recall_score , confusion_matrix
from sklearn.model_selection import GridSearchCV
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [7]:
import pandas as pd

df=pd.read_csv('C:/1차data/3.22.csv',encoding='cp949')
df

,고객번호,성별,연령대,거주지역,경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),...,D번제휴사구매비율(%),A_구매횟수,B_구매횟수,C_구매횟수,D_구매횟수,A_총구매액,B_총구매액,C_총구매액,D_총구매액,분기증감확인
0,1,1,5,1,15,0,0,2.86,27.70,66.92,...,0.00,874,64,119,0,1,7,3,4,0
1,2,1,5,0,8,0,0,3.64,36.73,53.35,...,9.90,1080,16,0,20,1,8,10,1,0
2,3,1,5,0,0,0,0,4.47,95.53,0.00,...,0.00,1,2,1188,0,10,10,3,8,0
3,4,0,5,1,3,0,0,2.72,26.13,66.48,...,0.00,649,126,155,0,4,6,4,8,0
4,6,0,5,3,0,0,0,4.99,45.59,40.38,...,0.00,361,1193,39,0,4,3,4,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,0,1,5,15.53,55.08,0.00,...,50.17,427,302,11,84,6,7,7,1,0
18862,19334,1,2,3,30,1,0,13.88,66.70,0.00,...,0.00,3,1674,287,0,8,2,4,5,0
18863,19335,0,2,0,0,1,0,16.72,53.31,0.00,...,0.00,10,1496,367,0,7,2,3,5,1
18864,19336,0,2,1,0,0,0,10.66,30.64,54.74,...,8.74,434,1,0,5,3,10,9,1,1
18865,19337,1,1,1,0,0,0,6.46,93.54,0.00,...,0.00,5,11,1305,0,9,8,3,10,1

In [13]:
df.columns

Index(['고객번호', '성별', '연령대', '거주지역', '경쟁사이용횟수', '멤버쉽보유', '온라인이용횟수',
       '1번품목구매비율(%)', '2번품목구매비율(%)', '3번품목구매비율(%)', '4번품목구매비율(%)', '편의품구매횟수',
       '선매품구매횟수', '전문품구매횟수', '기타구매횟수', '편의품구매등급', '선매품구매등급', '전문품구매등급',
       '기타구매등급', '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)',
       '5기구매비율(%)', '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)', '1기구매등급', '2기구매등급',
       '3기구매등급', '4기구매등급', '5기구매등급', '6기구매등급', '7기구매등급', '8기구매등급', '1기구매횟수',
       '2기구매횟수', '3기구매횟수', '4기구매횟수', '5기구매횟수', '6기구매횟수', '7기구매횟수', '8기구매횟수',
       'A제휴사구매비율(%)', 'B제휴사구매비율(%)', 'C제휴사구매비율(%)', 'D번제휴사구매비율(%)', 'A_구매횟수',
       'B_구매횟수', 'C_구매횟수', 'D_구매횟수', 'A_총구매액', 'B_총구매액', 'C_총구매액', 'D_총구매액',
       '분기증감확인'],
      dtype='object')

In [14]:
from sklearn.preprocessing import StandardScaler
stcol=['1번품목구매비율(%)', '2번품목구매비율(%)',
       '3번품목구매비율(%)', '4번품목구매비율(%)',
      '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)', '5기구매비율(%)',
       '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)',
      '경쟁사이용횟수','멤버쉽보유','온라인이용횟수','A제휴사구매비율(%)',
       'B제휴사구매비율(%)', 'C제휴사구매비율(%)', 'D번제휴사구매비율(%)',
      '1기구매횟수',
       '2기구매횟수', '3기구매횟수', '4기구매횟수', '5기구매횟수', '6기구매횟수', '7기구매횟수', '8기구매횟수',
      'A_구매횟수',
       'B_구매횟수', 'C_구매횟수', 'D_구매횟수','편의품구매횟수',
       '선매품구매횟수', '전문품구매횟수', '기타구매횟수']

for i in stcol:
    sc = StandardScaler()
    sc.fit(df[[i]])
    df[i] = sc.transform(df[[i]])
df

,고객번호,성별,연령대,거주지역,경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),...,D번제휴사구매비율(%),A_구매횟수,B_구매횟수,C_구매횟수,D_구매횟수,A_총구매액,B_총구매액,C_총구매액,D_총구매액,분기증감확인
0,1,1,5,1,3.784157,-0.652472,-0.424659,-0.630974,-0.755058,1.078629,...,-0.350180,1.699882,-0.776357,-0.416205,-0.124089,1,7,3,4,0
1,2,1,5,0,1.828781,-0.652472,-0.424659,-0.525165,-0.394411,0.679567,...,0.970125,2.311979,-0.834875,-0.549344,0.498494,1,8,10,1,0
2,3,1,5,0,-0.405935,-0.652472,-0.424659,-0.412574,1.953988,-0.889331,...,-0.350180,-0.894102,-0.851943,0.779811,-0.124089,10,10,3,8,0
3,4,0,5,1,0.432083,-0.652472,-0.424659,-0.649966,-0.817762,1.065689,...,-0.350180,1.031329,-0.700771,-0.375927,-0.124089,4,6,4,8,0
4,6,0,5,3,-0.405935,-0.652472,-0.424659,-0.342034,-0.040554,0.298150,...,-0.350180,0.175582,0.600035,-0.505710,-0.124089,4,3,4,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,-0.405935,1.068660,-0.084953,1.087744,0.338465,-0.889331,...,6.340700,0.371690,-0.486205,-0.537037,2.490763,6,7,7,1,0
18862,19334,1,2,3,7.974248,1.068660,-0.424659,0.863918,0.802553,-0.889331,...,-0.350180,-0.888160,1.186434,-0.228243,-0.124089,8,2,4,5,0
18863,19335,0,2,0,-0.405935,1.068660,-0.424659,1.249171,0.267773,-0.889331,...,-0.350180,-0.867360,0.969430,-0.138738,-0.124089,7,2,3,5,1
18864,19336,0,2,1,-0.405935,-0.652472,-0.424659,0.427116,-0.637638,0.720444,...,0.815422,0.392490,-0.853162,-0.549344,0.031557,3,10,9,1,1
18865,19337,1,1,1,-0.405935,-0.652472,-0.424659,-0.142625,1.874509,-0.889331,...,-0.350180,-0.882217,-0.840971,0.910712,-0.124089,9,8,3,10,1

In [16]:
lst=['성별','연령대','거주지역']

ddf=pd.get_dummies(df[lst[0]])
ddf.columns=['성별1','성별2']
onehot=pd.concat([df,ddf],axis=1)    
onehot

ddf=pd.get_dummies(df[lst[1]])
ddf.columns=['연령대1','연령대2','연령대3','연령대4','연령대5','연령대6']


ddf=pd.get_dummies(df[lst[2]])
ddf.columns=['거주1','거주2','거주3','거주4',]
onehot=pd.concat([onehot,ddf],axis=1)    
onehot

,고객번호,성별,연령대,거주지역,경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),...,B_총구매액,C_총구매액,D_총구매액,분기증감확인,성별1,성별2,거주1,거주2,거주3,거주4
0,1,1,5,1,3.784157,-0.652472,-0.424659,-0.630974,-0.755058,1.078629,...,7,3,4,0,0,1,0,1,0,0
1,2,1,5,0,1.828781,-0.652472,-0.424659,-0.525165,-0.394411,0.679567,...,8,10,1,0,0,1,1,0,0,0
2,3,1,5,0,-0.405935,-0.652472,-0.424659,-0.412574,1.953988,-0.889331,...,10,3,8,0,0,1,1,0,0,0
3,4,0,5,1,0.432083,-0.652472,-0.424659,-0.649966,-0.817762,1.065689,...,6,4,8,0,1,0,0,1,0,0
4,6,0,5,3,-0.405935,-0.652472,-0.424659,-0.342034,-0.040554,0.298150,...,3,4,8,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,19333,0,1,0,-0.405935,1.068660,-0.084953,1.087744,0.338465,-0.889331,...,7,7,1,0,1,0,1,0,0,0
18862,19334,1,2,3,7.974248,1.068660,-0.424659,0.863918,0.802553,-0.889331,...,2,4,5,0,0,1,0,0,0,1
18863,19335,0,2,0,-0.405935,1.068660,-0.424659,1.249171,0.267773,-0.889331,...,2,3,5,1,1,0,1,0,0,0
18864,19336,0,2,1,-0.405935,-0.652472,-0.424659,0.427116,-0.637638,0.720444,...,10,9,1,1,1,0,0,1,0,0
18865,19337,1,1,1,-0.405935,-0.652472,-0.424659,-0.142625,1.874509,-0.889331,...,8,3,10,1,0,1,0,1,0,0

In [18]:
onehot.corr()['분기증감확인'].sort_values()

8기구매등급      -0.352067
1기구매횟수      -0.307813
1기구매비율(%)   -0.282714
2기구매횟수      -0.205102
7기구매등급      -0.175699
               ...
8기구매횟수       0.111083
선매품구매횟수      0.111342
1기구매등급       0.206731
8기구매비율(%)    0.330984
분기증감확인       1.000000
Name: 분기증감확인, Length: 62, dtype: float64

In [150]:
X.columns

Index(['성별1', '성별2', '연령대1', '연령대2', '연령대3', '연령대4', '연령대5', '연령대6', '거주1',
       '거주2', '거주3', '거주4'],
      dtype='object')

In [19]:
# X = df.drop(['고객번호','분기증감확인'],axis=1)
# y=df[['분기증감확인']]
# X = onehot.drop(['1번품목구매비율(%)', '2번품목구매비율(%)', '3번품목구매비율(%)', '4번품목구매비율(%)', '경쟁사이용횟수',
#        '멤버쉽보유', '온라인이용횟수', '1기구매비율(%)', '2기구매비율(%)', '3기구매비율(%)', '4기구매비율(%)',
#        '5기구매비율(%)', '6기구매비율(%)', '7기구매비율(%)', '8기구매비율(%)','고객번호','분기증감확인','성별','연령대','거주지역', '거주1',
#        '거주2', '거주3', '거주4', '연령대1', '연령대2', '연령대3', '연령대4', '연령대5', '연령대6',	'성별1','성별2'],axis=1)

X = onehot.drop(['고객번호','분기증감확인','성별','연령대','거주지역'],axis=1)
y=df[['분기증감확인']]
X

,경쟁사이용횟수,멤버쉽보유,온라인이용횟수,1번품목구매비율(%),2번품목구매비율(%),3번품목구매비율(%),4번품목구매비율(%),편의품구매횟수,선매품구매횟수,전문품구매횟수,...,A_총구매액,B_총구매액,C_총구매액,D_총구매액,성별1,성별2,거주1,거주2,거주3,거주4
0,3.784157,-0.652472,-0.424659,-0.630974,-0.755058,1.078629,-0.835903,-0.758802,1.593074,-0.280671,...,1,7,3,4,0,1,0,1,0,0
1,1.828781,-0.652472,-0.424659,-0.525165,-0.394411,0.679567,-0.596377,-0.607468,1.283442,0.109323,...,1,8,10,1,0,1,1,0,0,0
2,-0.405935,-0.652472,-0.424659,-0.412574,1.953988,-0.889331,-0.996436,-0.145124,-1.185008,-0.378170,...,10,10,3,8,0,1,1,0,0,0
3,0.432083,-0.652472,-0.424659,-0.649966,-0.817762,1.065689,-0.698940,-0.690880,-0.023890,-0.280671,...,4,6,4,8,1,0,0,1,0,0
4,-0.405935,-0.652472,-0.424659,-0.342034,-0.040554,0.298150,-0.420556,0.031234,0.474960,0.206821,...,4,3,4,8,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18861,-0.405935,1.068660,-0.084953,1.087744,0.338465,-0.889331,0.875812,-0.752844,-1.133402,-0.378170,...,6,7,7,1,1,0,1,0,0,0
18862,7.974248,1.068660,-0.424659,0.863918,0.802553,-0.889331,0.240687,0.703301,-0.797969,-0.378170,...,8,2,4,5,0,1,0,0,0,1
18863,-0.405935,1.068660,-0.424659,1.249171,0.267773,-0.889331,0.912760,0.316029,0.010513,-0.378170,...,7,2,3,5,1,0,1,0,0,0
18864,-0.405935,-0.652472,-0.424659,0.427116,-0.637638,0.720444,-0.744170,-1.494024,0.500763,0.109323,...,3,10,9,1,1,0,0,1,0,0
18865,-0.405935,-0.652472,-0.424659,-0.142625,1.874509,-0.889331,-0.996436,0.000252,-1.116201,-0.378170,...,9,8,3,10,0,1,0,1,0,0

In [30]:
def est(y_test,pred,pred_proba):
    con=confusion_matrix(y_test,pred)
    acc=accuracy_score(y_test,pred)
    pre=precision_score(y_test,pred)
    rec=recall_score(y_test,pred)
    f1=f1_score(y_test,pred)
    roc=roc_auc_score(y_test,pred_proba)
    print('오차행렬\n',con.round(3))
    print('정확도 :',acc.round(3))
    print('정밀도 :',pre.round(3))
    print('재현율 :',rec.round(3))
    print('f1점수:',f1.round(3))
    print('roc_auc :',roc.round(3))
    print()
    print()

In [32]:
%%time
X =df.drop(['고객번호','분기증감확인','성별','연령대','거주지역'],axis=1)
y=df[['분기증감확인']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=10)

def est(y_test,pred,pred_proba):
    con=confusion_matrix(y_test,pred)
    acc=accuracy_score(y_test,pred)
    pre=precision_score(y_test,pred)
    rec=recall_score(y_test,pred)
    f1=f1_score(y_test,pred)
    roc=roc_auc_score(y_test,pred_proba)
    print('오차행렬\n',con.round(3))
    print('정확도 :',acc.round(3))
    print('정밀도 :',pre.round(3))
    print('재현율 :',rec.round(3))
    print('f1점수:',f1.round(3))
    print('roc_auc :',roc.round(3))
    print()
    print()
    
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train , y_train)
pred = dt_clf.predict(X_test)
pred_proba = dt_clf.predict_proba(X_test)[:,1]
print('결정트리')
est(y_test,pred,pred_proba)

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
pred_proba = rf_clf.predict_proba(X_test)[:,1]
print('랜덤포레스트')
est(y_test,pred,pred_proba)

                                                                  

lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:,1]
print('로지스틱회귀')
est(y_test,pred,pred_proba)

lgbm_wrapper = LGBMClassifier(n_estimators=400)
evals = [(X_test,y_test)]
lgbm_wrapper.fit(X_train, y_train, eval_set=evals, verbose=False)
pred = lgbm_wrapper.predict(X_test)
pred_proba = lgbm_wrapper.predict_proba(X_test)[:,1]
print('LGBM')
est(y_test,pred,pred_proba)


evals = [(X_test,y_test)]
xgb_wrapper = XGBClassifier(n_estimators=400, learning_rate=0.1, max_depth=3)
xgb_wrapper.fit(X_train,y_train, early_stopping_rounds = 100, eval_set=evals, eval_metric='logloss', verbose=False)
pred = xgb_wrapper.predict(X_test)
pred_proba = xgb_wrapper.predict_proba(X_test)[:,1]
print('XGB')
est(y_test,pred,pred_proba)


k_model = KNeighborsClassifier(n_neighbors=40)
k_model.fit(X_train,y_train)
pred = k_model.predict(X_test)
pred_proba = k_model.predict_proba(X_test)[:,1]
print('KNN')
est(y_test,pred,pred_proba)




lr_clf = LogisticRegression()
knn_clf = KNeighborsClassifier(n_neighbors=8)
vo_clf = VotingClassifier( estimators=[('LR',lr_clf),('KNN',knn_clf)] , voting='soft' )
vo_clf.fit(X_train , y_train)
pred = vo_clf.predict(X_test)
pred_proba = vo_clf.predict_proba(X_test)[:,1]
print('KNN + 로지스틱회귀 앙상블')
est(y_test,pred,pred_proba)

결정트리
오차행렬
 [[1912  205]
 [ 230 1427]]
정확도 : 0.885
정밀도 : 0.874
재현율 : 0.861
f1점수: 0.868
roc_auc : 0.882


랜덤포레스트
오차행렬
 [[2012  105]
 [ 184 1473]]
정확도 : 0.923
정밀도 : 0.933
재현율 : 0.889
f1점수: 0.911
roc_auc : 0.981


로지스틱회귀
오차행렬
 [[2006  111]
 [ 135 1522]]
정확도 : 0.935
정밀도 : 0.932
재현율 : 0.919
f1점수: 0.925
roc_auc : 0.984


LGBM
오차행렬
 [[2042   75]
 [  66 1591]]
정확도 : 0.963
정밀도 : 0.955
재현율 : 0.96
f1점수: 0.958
roc_auc : 0.996


XGB
오차행렬
 [[2056   61]
 [  67 1590]]
정확도 : 0.966
정밀도 : 0.963
재현율 : 0.96
f1점수: 0.961
roc_auc : 0.996


KNN
오차행렬
 [[1980  137]
 [ 626 1031]]
정확도 : 0.798
정밀도 : 0.883
재현율 : 0.622
f1점수: 0.73
roc_auc : 0.905


KNN + 로지스틱회귀 앙상블
오차행렬
 [[1994  123]
 [ 157 1500]]
정확도 : 0.926
정밀도 : 0.924
재현율 : 0.905
f1점수: 0.915
roc_auc : 0.977


Wall time: 18.4 s

In [ ]:
svm_model = svm.SVC(kernel='rbf')
svm_model.fit(X_train, y_train)
pred = svm_model.predict(X_test)
pred_proba = svm_model.predict_proba(X_test)[:,1]
# print('SVM')
est(y_test,pred,pred_proba)

# svm_model = svm.SVC(kernel='rbf')
# svm_model.fit(X_train, y_train)
# pred = svm_model.predict(X_test)
# pred_proba = svm_model.predict_proba(X_test)[:,1]
# print('SVM')
# est(y_test,pred,pred_proba)