In [12]:
import pandas as pd
import glob ,os

path = r'C:\GitHub\Mycakd5\m8_머신러닝응용\OpinosisDataset1.0\topics'                     
all_files = glob.glob(os.path.join(path, "*.data"))    
filename_list = []
opinion_text = []
all_files
for file_ in all_files:
    df = pd.read_table(file_,index_col=None, header=0,encoding='latin1')
    filename_ = file_.split('\\')[-1]
    filename = filename_.split('.')[0]
    filename_list.append(filename)
    
    opinion_text.append(df.to_string())



document_df = pd.DataFrame({'filename':filename_list, 'opinion_text':opinion_text})
document_df.head()

,filename,opinion_text
0,accuracy_garmin_nuvi_255W_gps,...
1,bathroom_bestwestern_hotel_sfo,...
2,battery-life_amazon_kindle,...
3,battery-life_ipod_nano_8gb,...
4,battery-life_netbook_1005ha,...

In [20]:
from nltk.stem import WordNetLemmatizer
import nltk
import string

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

lemmar = WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmar.lemmatize(token) for token in tokens]

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.05, max_df=0.85 )

#opinion_text 컬럼값으로 feature vectorization 수행
feature_vect = tfidf_vect.fit_transform(document_df['opinion_text'])

In [62]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=2, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

In [63]:
document_df['cluster_label'] = cluster_label
document_df.head()

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,...,1
1,bathroom_bestwestern_hotel_sfo,...,0
2,battery-life_amazon_kindle,...,1
3,battery-life_ipod_nano_8gb,...,1
4,battery-life_netbook_1005ha,...,1

In [64]:
document_df[document_df['cluster_label']==0]

,filename,opinion_text,cluster_label
1,bathroom_bestwestern_hotel_sfo,...,0
13,food_holiday_inn_london,...,0
14,food_swissotel_chicago,...,0
15,free_bestwestern_hotel_sfo,...,0
20,location_bestwestern_hotel_sfo,...,0
21,location_holiday_inn_london,...,0
24,parking_bestwestern_hotel_sfo,...,0
28,price_holiday_inn_london,...,0
30,rooms_bestwestern_hotel_sfo,...,0
31,rooms_swissotel_chicago,...,0
32,room_holiday_inn_london,...,0
38,service_bestwestern_hotel_sfo,...,0
39,service_holiday_inn_london,...,0
40,service_swissotel_hotel_chicago,...,0
45,staff_bestwestern_hotel_sfo,...,0
46,staff_swissotel_chicago,...,0

In [65]:
document_df[document_df['cluster_label']==1]

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,...,1
2,battery-life_amazon_kindle,...,1
3,battery-life_ipod_nano_8gb,...,1
4,battery-life_netbook_1005ha,...,1
5,buttons_amazon_kindle,...,1
6,comfort_honda_accord_2008,...,1
7,comfort_toyota_camry_2007,...,1
8,directions_garmin_nuvi_255W_gps,...,1
9,display_garmin_nuvi_255W_gps,...,1
10,eyesight-issues_amazon_kindle,...,1
11,features_windows7,...,1
12,fonts_amazon_kindle,...,1
16,gas_mileage_toyota_camry_2007,...,1
17,interior_honda_accord_2008,...,1
18,interior_toyota_camry_2007,...,1
19,keyboard_netbook_1005ha,...,1
22,mileage_honda_accord_2008,...,1
23,navigation_amazon_kindle,...,1
25,performance_honda_accord_2008,...,1
26,performance_netbook_1005ha,...,1
27,price_amazon_kindle,...,1
29,quality_toyota_camry_2007,...,1
33,satellite_garmin_nuvi_255W_gps,...,1
34,screen_garmin_nuvi_255W_gps,...,1
35,screen_ipod_nano_8gb,...,1
36,screen_netbook_1005ha,...,1
37,seats_honda_accord_2008,...,1
41,size_asus_netbook_1005ha,...,1
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it a...,1
43,speed_garmin_nuvi_255W_gps,...,1
44,speed_windows7,...,1
47,transmission_toyota_camry_2007,...,1
48,updates_garmin_nuvi_255W_gps,...,1
49,video_ipod_nano_8gb,...,1
50,voice_garmin_nuvi_255W_gps,...,1

In [60]:
document_df[document_df['cluster_label']==2]

,filename,opinion_text,cluster_label
45,staff_bestwestern_hotel_sfo,...,2
46,staff_swissotel_chicago,...,2

In [61]:
document_df[document_df['cluster_label']==8]

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,...,8
8,directions_garmin_nuvi_255W_gps,...,8
9,display_garmin_nuvi_255W_gps,...,8
33,satellite_garmin_nuvi_255W_gps,...,8
43,speed_garmin_nuvi_255W_gps,...,8
48,updates_garmin_nuvi_255W_gps,...,8
50,voice_garmin_nuvi_255W_gps,...,8

In [ ]:
#과제 적절한 군집수로 조정하여 적절성 여부를 검증하세요

In [ ]:
#과제 군집별 핵심 단어 및 파일 리스트 추출하세요.